name: Convert Resume to PDF
on:
  push:
    paths-ignore:
      - '**/CSResumeLatest.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup Env
        run: pip install mdpdf

      - name: Convert to PDF
        run: mdpdf -o CSResumeLatest.pdf README.md

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CSResumeLatest.pdf
          git commit -m "Add PDF version of README.md"
          git remote add origin_with_token https://github.com/${{ github.repository }}.git
          git push --set-upstream origin_with_token $GITHUB_REF